using BinancePayConnector.Core.Models.Abstractions;

namespace BinancePayConnector.Core.Models.C2B.RestApi.ProfitSharing.QuerySplit;

/// <summary>
/// You can see this in official documentation: <see href="https://developers.binance.com/docs/binance-pay/api-profitshare-query-split#request-parameters"/>.
/// </summary>
/// <param name="MerchantRequestId">The unique identifier from the merchant for this split request.</param>
/// <param name="PrepayOrderId">The unique order id generated by binance when you create the order.</param>
public record QuerySplitRequest(
    string MerchantRequestId,
    string PrepayOrderId
) : IRequest<QuerySplitResult>;
