using BinancePayConnector.MediatrStyle.Abstractions;
using BinancePayConnector.Models.C2B.Common.Enums;

namespace BinancePayConnector.Models.C2B.RestApi.TransferFund.TransferFund;

/// <summary>
/// You can see this in official documentation: <see href="https://developers.binance.com/docs/binance-pay/api-wallet-transfer#request-parameters"/>.
/// </summary>
/// <param name="RequestId">Represents the unique ID of each transfer request. Generated by the merchant</param>
/// <param name="Currency">Enum values from: <see cref="Assets"/>.</param>
/// <param name="Amount">The transfer amount.</param>
/// <param name="TransferType">TO_MAIN means to spot wallet, TO_PAY means to funding wallet. Enum values from <see cref="Enums.TransferType"/>.</param>
public sealed record TransferFundRequest(
    string RequestId,
    string Currency,
    string Amount,
    string TransferType
) : IRequest<TransferFundResult>;
