namespace BinancePayConnector.Models.C2B.RestApi.DirectDebit.CreateContract;

/// <summary>
/// You can see this in official documentation: <see href="https://developers.binance.com/docs/binance-pay/api-directdebit-create-contract#dataobject"/>.
/// </summary>
/// <param name="MerchantId">Merchant id in binance</param>
/// <param name="PreContractId">Unique id generated by binance.</param>
/// <param name="ContractEndTime">Contract will be expired at this time.</param>
/// <param name="RequestExpireTime">User can not sign contract after this time.</param>
/// <param name="QrContent">Qr content info.</param>
/// <param name="QrcodeLink">Qr code img link.</param>
/// <param name="Deeplink">Deeplink to open binance app to sign contract.</param>
public sealed record CreateContractResult(
    long MerchantId,
    string PreContractId,
    long ContractEndTime,
    long RequestExpireTime,
    string QrContent,
    string QrcodeLink,
    string Deeplink
);
