namespace BinancePayConnector.Models.C2B.RestApi.SubMerchant.Common;

/// <summary>
/// You can see this in official documentation: <see href="https://developers.binance.com/docs/binance-pay/api-submerchant-add#addsubmerchantresponse"/>.
/// </summary>
/// <param name="SubMerchantId">Unique sub-merchant id generated by payment</param>
public sealed record AddSubMerchantResult(
    long SubMerchantId    
);
