using BinancePayConnector.Core.Models.C2B.RestApi.DirectDebit.Common.Enums;

namespace BinancePayConnector.Core.Models.C2B.RestApi.DirectDebit.Payment;

/// <summary>
/// You can see this in official documentation: <see href="https://developers.binance.com/docs/binance-pay/api-directdebit-pay-apply#dataobject"/>.
/// </summary>
/// <param name="OrderId">Unique id generated by binance.</param>
/// <param name="PrepayId">Prepay id, the same as returned by the create order API.</param>
/// <param name="MerchantRequestId">The order id, Unique identifier for the request.</param>
/// <param name="AppliedTime">Transaction time in milliseconds.</param>
/// <param name="Status">Enum values from: <see cref="OrderStatus"/>.</param>
public sealed record PaymentResult(
    string OrderId,
    string PrepayId,
    string MerchantRequestId,
    long AppliedTime,
    string Status
);
