using BinancePayConnector.Core.Models.C2B.RestApi.Order.QueryOrder.Enums;

namespace BinancePayConnector.Core.Models.C2B.RestApi.Order.QueryOrder.QueryOrderResultModel;

/// <summary>
/// You can see this in official documentation: <see href="https://developers.binance.com/docs/binance-pay/api-order-query-v2#queryorderresult"/>
/// </summary>
/// <param name="MerchantId">The merchant account id, issued when merchant been created at Binance.</param>
/// <param name="PrepayId">Unique id generated by binance.</param>
/// <param name="MerchantTradeNo">Letter or digit, no other symbol allowed, can not be empty if prepayId is empty.</param>
/// <param name="Status">Order status from enum values <see cref="OrderStatus"/>.</param>
/// <param name="Currency">Order currency.</param>
/// <param name="OrderAmount">Limitation refer to Create Order API order amount.</param>
/// <param name="CreateTime">Timestamp when order was created.</param>
/// <param name="TransactionId">Issued once the payment is successful.</param>
/// <param name="OpenUserId">Consumer unique id.</param>
/// <param name="PassThroughInfo">Pass through info, from the create order api.</param>
/// <param name="TransactTime">Timestamp when transaction happened.</param>
public sealed record QueryOrderResult(
    long MerchantId,
    string PrepayId,
    string MerchantTradeNo,
    string Status,
    string Currency,
    string OrderAmount,
    long CreateTime,
    string? TransactionId = null,
    string? OpenUserId = null,
    string? PassThroughInfo = null,
    long? TransactTime = null,
    PaymentInfo? PaymentInfo = null
);
